name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: "Documentation"
    labels:
      - 'documentation'
  - title: 'Features'
    labels:
      - 'new feature'
      - 'enhancement'
      - 'performance improvement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes
  $CHANGES
